REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Новички', 5, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Новички', 5, 'ru');
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Опытные пользователи', 6, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Опытные пользователи', 6, 'ru');
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Продвинутые пользователи', 7, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Продвинутые пользователи', 7, 'ru');
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Партнеры компании', 8, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Партнеры компании', 8, 'ru');
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('VIP', 9, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('VIP', 9, 'ru');
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('A', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Контент-менеджер', 10, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Контент-менеджер', 10, 'ru');
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Менеджер товаров', 11, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Менеджер товаров', 11, 'ru');
UPDATE cscart_usergroups SET `type` = 'A', `status` = 'A' WHERE usergroup_id = 11;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Менеджер товаров' WHERE usergroup_id = 11 AND lang_code = 'ru';
UPDATE cscart_usergroups SET `type` = 'A', `status` = 'A' WHERE usergroup_id = 10;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Content manager' WHERE usergroup_id = 10 AND lang_code = 'en';
DELETE FROM cscart_usergroup_privileges WHERE usergroup_id = 10;
UPDATE cscart_usergroups SET `type` = 'A', `status` = 'A' WHERE usergroup_id = 11;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Products manager' WHERE usergroup_id = 11 AND lang_code = 'en';
DELETE FROM cscart_usergroup_privileges WHERE usergroup_id = 11;
UPDATE cscart_usergroups SET `type` = 'C', `status` = 'A' WHERE usergroup_id = 5;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Newbies' WHERE usergroup_id = 5 AND lang_code = 'en';
DELETE FROM cscart_usergroups WHERE usergroup_id IN (6);
DELETE FROM cscart_usergroup_descriptions WHERE usergroup_id IN (6);
DELETE FROM cscart_usergroup_privileges WHERE usergroup_id IN (6);
DELETE FROM cscart_usergroup_links WHERE usergroup_id IN (6);
DELETE FROM cscart_product_prices WHERE usergroup_id IN (6);
UPDATE cscart_usergroups SET `type` = 'C', `status` = 'A' WHERE usergroup_id = 7;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Advanced users' WHERE usergroup_id = 7 AND lang_code = 'en';
UPDATE cscart_usergroups SET `type` = 'C', `status` = 'A' WHERE usergroup_id = 8;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Partners' WHERE usergroup_id = 8 AND lang_code = 'en';
REPLACE INTO cscart_usergroups (`type`, `status`) VALUES ('C', 'A');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Masters', 12, 'en');
REPLACE INTO cscart_usergroup_descriptions (`usergroup`, `usergroup_id`, `lang_code`) VALUES ('Masters', 12, 'ru');
UPDATE cscart_usergroups SET `type` = 'C', `status` = 'A' WHERE usergroup_id = 12;
UPDATE cscart_usergroup_descriptions SET `usergroup` = 'Опытные пользователи' WHERE usergroup_id = 12 AND lang_code = 'ru';
INSERT INTO cscart_settings_objects (`object_id`, `value`) VALUES (6294, 'JXHSA-XXX1A-NXBXA-NMVU1') ON DUPLICATE KEY UPDATE `object_id` = 6294, `value` = 'JXHSA-XXX1A-NXBXA-NMVU1';
DELETE FROM cscart_settings_vendor_values WHERE object_id = 6294 AND company_id = 1;
INSERT INTO cscart_settings_objects (`object_id`, `value`) VALUES (6295, 'Y') ON DUPLICATE KEY UPDATE `object_id` = 6295, `value` = 'Y';
DELETE FROM cscart_settings_vendor_values WHERE object_id = 6295 AND company_id = 1;
INSERT INTO cscart_settings_objects (`object_id`, `value`) VALUES (6296, '#M#10=Y') ON DUPLICATE KEY UPDATE `object_id` = 6296, `value` = '#M#10=Y';
DELETE FROM cscart_settings_vendor_values WHERE object_id = 6296 AND company_id = 1;
INSERT INTO cscart_settings_objects (`object_id`, `value`) VALUES (6297, '#M#7=Y') ON DUPLICATE KEY UPDATE `object_id` = 6297, `value` = '#M#7=Y';
DELETE FROM cscart_settings_vendor_values WHERE object_id = 6297 AND company_id = 1;
